config/routes.rb
Rails.application.routes.draw do
  root "courses#index"

  resources :courses, only: [:show]
  resources :students, except: [:destroy]
  resources :logins, only: [:new, :create, :destroy]

  post "enroll_in_course", to: "student_courses#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :short_name, presence: true, uniqueness: true
  validates :name, presence: true
  validates :description, presence: true

  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, presence: true

  has_secure_password

  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Student.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    user = Student.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully signed in"
      redirect_to student_path(user)
    else
      flash.now[:danger] = "We could not find a profile matching the provided credentials"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully signed out"
    redirect_to request.referer
  end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  def create
    course_to_add = Course.find(params[:course_id])

    unless current_user.courses.include?(course_to_add)
      current_user.courses << course_to_add
      flash[:success] = "You are now enrolled in #{course_to_add.short_name}: #{course_to_add.name}"
      redirect_to student_path(current_user)
    else
      flash[:error] = "We were not able to enroll you in #{course_to_add.name}"
      redirect_to root_path
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:edit, :show, :update]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @students = Student.all
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      flash[:success] = "Thanks for signing up, #{@student.name}"
      session[:user_id] = @student.id
      redirect_to student_path(@student)
    else
      flash[:error] = "There was an error creating your profile. <br/> #{errors_string}"
      render "new"
    end
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def show
  end

  def update
    if @student.update(student_params)
      flash[:success] = "#{@student.name}'s profile has been updated"
      redirect_to student_path(@student)
    else
      flash[:error] = "There was an error updating your profile. <br/> #{errors_string}"
      render "edit"
    end
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def errors_string
    @student.errors.full_messages.join(", and ")
  end

  def student_params
    params.require(:student).permit(:name, :email, :password)
  end

  def require_same_user
    if current_user != @student
      flash[:error] = "You do not have permission to perform this action"
      redirect_to new_login_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.haml
.row
  .col.s12
    %h1.center-align Course Listing

.row
  - @courses.each do |course|
    .col.s6.m6
      .card.blue-grey.darken-1
        .card-content.card-content--min-height.white-text
          %span.card-title #{course.short_name}: #{course.name}
          %p= course.description
        .card-action
          = link_to 'Info', course_path(course)
          - if logged_in?
            - if current_user.courses.include?(course)
              ENROLLED
            - else
              = link_to 'Enroll', enroll_in_course_path(course_id: course.id), method: :post

app/views/courses/show.html.haml
.row
  .col.s12
    %h1.center-align #{@course.short_name}: #{@course.name}
    %h4.center-align= @course.description

.row
  .col.s12
    %h4.center-align Students Enrolled

    - @course.students.each do |student|
      .col.s6.m6
        .card.blue-grey.darken-1
          .card-content.white-text
            %span.card-title #{student.name}
            %p= student.email
          .card-action
            = link_to 'View Profile', student_path(student)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
    %title Tech University
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %header
      %nav
        .container
          .nav-wrapper
            = link_to 'Tech University', root_path, class: 'brand-logo right'
            %ul#nav-mobile.left.hide-on-med-and-down
              %li= link_to 'Courses', root_path
              %li= link_to 'Students', students_path
              - if logged_in?
                %li= link_to 'Profile', student_path(current_user)
                %li= link_to 'Sign Out', login_path(current_user), method: :delete
              - else
                %li= link_to 'Sign In', new_login_path
                %li= link_to 'Sign Up', new_student_path

    %main
      - flash.each do |type, message|
        .row{ data: { flash_message: '' } }
          .col.s12
            .card-panel{ class: type == 'error' ? 'deep-orange' : 'teal' }
              .white-text
                = message.html_safe

      .container
        = yield

    %footer.page-footer
      .container
        .row
          .col.l6.s12
            %h5.white-text Tech University
            %p.grey-text.text-lighten-4 The future of development training
          .col.l4.offset-l2.s12
            %h5.white-text Information
            %ul
              %li= link_to 'Help', '#', class: 'grey-text text-lighten-3'
              %li= link_to 'About', '#', class: 'grey-text text-lighten-3'
              %li= link_to 'Contact Us', '#', class: 'grey-text text-lighten-3'
      .footer-copyright
        .container
          © #{Date.current.year} Tech University

app/views/logins/new.html.haml
.row
  .col.s12
    %h1.center-align Sign In

.row
  = form_with url: logins_path, local: true, class: 'col s6 offset-s3' do |form|
    .row
      .input-field.col.s12
        = form.text_field :email, required: true
        = form.label :email
    .row
      .input-field.col.s12
        = form.password_field :password, required: true
        = form.label :password
    .row
      .col.s12.right-align
        = button_tag type: 'submit', class: 'btn waves-effect waves-light' do
          Submit
          %i.material-icons.right send

app/views/students/_form.html.haml
.row
  = form_with model: @student, local: true, class: 'col s6 offset-s3' do |form|
    .row
      .input-field.col.s12
        = form.text_field :name, required: true
        = form.label :name
    .row
      .input-field.col.s12
        = form.email_field :email, required: true
        = form.label :email
    .row
      .input-field.col.s12
        = form.password_field :password, required: @student.new_record?
        = form.label :password
    .row
      .col.s12.right-align
        = button_tag type: 'submit', class: 'btn waves-effect waves-light' do
          - if @student.new_record?
            Submit
          - else
            Update
          %i.material-icons.right send

app/views/students/edit.html.haml
.row
  .col.s12
    %h1.center-align Edit #{@student.name}'s Profile

= render 'form'

app/views/students/index.html.haml
.row
  .col.s12
    %h1.center-align Students Directory

.row
  - @students.each do |student|
    .col.s6.m6
      .card.blue-grey.darken-1
        .card-content.white-text
          %span.card-title #{student.name}
          %p= student.email
          %p [ENROLLMENTS PLACEHOLDER]
        .card-action
          = link_to 'View Profile', student_path(student)

app/views/students/new.html.haml
.row
  .col.s12
    %h1.center-align Sign Up

= render 'form'

app/views/students/show.html.haml
.row
  .col.s12
    %h1.center-align #{@student.name}'s Profile

.row
  .col.s6.m6
    .card.blue-grey.darken-1
      .card-content.white-text
        %span.card-title #{@student.name}
        %p= @student.email
        %br
        %p Course Enrollments:
        %ul
          - @student.courses.each do |course|
            %li
              = link_to "#{course.short_name}: #{course.name}", course_path(course), class: 'white-text'
      - if logged_in? && current_user == @student
        .card-action
          = link_to 'Edit', edit_student_path(@student)